//User
export const FETCH_USER_REQUEST = '[User] FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = '[User] FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = '[User] FETCH_USER_FAILURE';
export const CHANGE_USER_PERMISSION = '[User] CHANGE_USER_PERMISSION';

//Products
export const FETCH_PRODUCTS_REQUEST = '[Products] FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = '[Products] FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = '[Products] FETCH_PRODUCTS_FAILURE';
export const DELETE_PRODUCTS = '[Products] DELETE_PRODUCTS';
export const DELETE_PRODUCT = '[Product] DELETE_PRODUCT';
export const ADD_PRODUCT = '[Product] ADD_PRODUCT';

//Form
export const STORE_FORM_FIELDS = '[Form] STORE_FORM_FIELDS';
export const CLEAR_FORM_FIELDS = '[Form] CLEAR_FORM_FIELDS';